version: "3.8"

services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker/nginx/self-signed.crt:/etc/nginx/self-signed.crt
      - ./docker/nginx/self-signed.key:/etc/nginx/self-signed.key
    networks:
      - app-network

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge